# Generated by Django 3.2.9 on 2021-12-05 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capacite', models.IntegerField()),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='none', max_length=30)),
                ('profil', models.CharField(choices=[('Locataire', 'Locataire'), ('Locateur', 'Locateur')], max_length=9)),
                ('genre', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='none', max_length=9)),
                ('lastTime', models.DateTimeField()),
                ('mdp', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ville',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ville', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nbr_personnes', models.IntegerField()),
                ('in_date', models.DateTimeField()),
                ('out_date', models.DateTimeField()),
                ('total', models.FloatField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('E', 'Expired')], max_length=9)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_app.chambre')),
                ('locataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ui_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='chambre',
            name='locateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_app.user'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_app.ville'),
        ),
    ]
