# Generated by Django 3.2.9 on 2021-12-06 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0002_auto_20211205_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='locataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locataire', to='ui_app.user'),
        ),
    ]
