# Generated by Django 3.2.9 on 2021-12-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passwordConfirm',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
